CREATE TABLE `contacts` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `name` varchar(255) default NULL,
  `email` varchar(255) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

INSERT INTO `contacts` (`name`,`email`) VALUES ("Cheryl","Nunc.commodo@faucibuslectus.net"),("Leandra","parturient.montes@eutemporerat.net"),("Lana","egestas@Duiscursusdiam.co.uk"),("Brett","fermentum.fermentum@facilisiSedneque.edu"),("Clementine","malesuada.augue.ut@elitpretiumet.ca"),("Gretchen","eget.dictum@Ut.ca"),("Mari","Phasellus.dapibus@molestieorcitincidunt.co.uk"),("Odysseus","pretium.aliquet.metus@risus.edu"),("Dana","eleifend.egestas@aliquet.ca"),("Hadley","et.nunc@Phasellus.org");
INSERT INTO `contacts` (`name`,`email`) VALUES ("Whilemina","sodales.elit@scelerisquenequesed.co.uk"),("Clark","scelerisque@risusDonecegestas.edu"),("Madison","arcu@Aliquamtinciduntnunc.co.uk"),("Preston","Sed.eu.eros@erat.edu"),("Leonard","congue.turpis@ultricies.org"),("Arden","et@mollisneccursus.ca"),("Sage","quam.vel.sapien@nonegestasa.co.uk"),("Isabelle","mauris.aliquam@miAliquam.edu"),("Jakeem","nisi.Cum@estac.ca"),("Timothy","penatibus@magna.ca");
INSERT INTO `contacts` (`name`,`email`) VALUES ("Kendall","Nunc@egetipsum.net"),("Fuller","cursus.diam@risusDonecnibh.co.uk"),("Nicole","massa.rutrum@quis.edu"),("Nehru","Aenean@liberoat.co.uk"),("Davis","elit@egetipsumSuspendisse.edu"),("Samson","enim.Nunc@nibhenim.net"),("Elvis","ac.turpis.egestas@malesuada.co.uk"),("Sheila","et.magnis@antedictumcursus.edu"),("Melvin","id.blandit@congue.org"),("Melyssa","sapien.cursus@ridiculus.com");
INSERT INTO `contacts` (`name`,`email`) VALUES ("Hu","interdum.Curabitur@Quisquevarius.co.uk"),("Linus","non.sollicitudin@orciluctus.edu"),("Len","lobortis.mauris@Nullamvitaediam.edu"),("Hu","vestibulum.nec.euismod@sapienmolestie.net"),("Ulla","est.tempor@nequeNullamnisl.co.uk"),("Alden","aliquet.metus.urna@ligula.org"),("Hakeem","ligula.tortor@aliquet.ca"),("Armando","leo@arcu.com"),("Geoffrey","sapien.molestie.orci@Duis.ca"),("Charde","vulputate.ullamcorper@etultrices.com");
INSERT INTO `contacts` (`name`,`email`) VALUES ("Chase","In.nec.orci@ornareelitelit.co.uk"),("Helen","fermentum.arcu.Vestibulum@morbitristiquesenectus.co.uk"),("Xerxes","lorem.vitae.odio@ipsum.com"),("Karen","lorem@Mauriseu.edu"),("Delilah","non.feugiat@volutpatnuncsit.com"),("Heather","Nulla.facilisi@elitEtiamlaoreet.edu"),("Marshall","Ut@luctuset.co.uk"),("Timothy","lacus.pede.sagittis@antelectusconvallis.net"),("Gavin","semper.egestas.urna@sagittis.net"),("Nayda","feugiat.metus.sit@facilisisvitaeorci.ca");
INSERT INTO `contacts` (`name`,`email`) VALUES ("Justin","lectus.pede.et@sed.com"),("Bruno","pellentesque@volutpat.edu"),("Frances","aliquet.Proin.velit@nec.ca"),("Jason","sem.molestie.sodales@vel.net"),("Melyssa","cursus@facilisisnonbibendum.com"),("Melodie","vel.quam.dignissim@adui.edu"),("Angelica","magna.malesuada@Integertincidunt.org"),("Timothy","lorem.vitae@arcuVestibulumut.co.uk"),("Gary","mauris@dapibusligulaAliquam.edu"),("Lucas","bibendum.sed.est@fringilla.ca");
INSERT INTO `contacts` (`name`,`email`) VALUES ("Ezekiel","Donec.felis@venenatisvel.org"),("Ashton","vulputate@nonbibendumsed.net"),("Sylvester","Donec@Integer.org"),("Eden","convallis.ante.lectus@malesuadavel.com"),("Mariam","at@arcuimperdietullamcorper.co.uk"),("Lacota","eu.ligula@scelerisquesedsapien.edu"),("Zachery","Phasellus.in@eu.co.uk"),("Meghan","nonummy.ultricies@ultricesposuere.edu"),("Jasper","fermentum.vel@mi.ca"),("Jasper","hendrerit@lectusjusto.co.uk");
INSERT INTO `contacts` (`name`,`email`) VALUES ("Jolene","lorem@magnaCrasconvallis.ca"),("Kelsie","Integer@Sed.edu"),("Dakota","Cras@eratvitaerisus.edu"),("Ingrid","Vestibulum@orci.ca"),("Lois","odio@eudui.org"),("Leila","Aliquam@ipsumSuspendisse.org"),("Zoe","lacus.Quisque.purus@antedictum.co.uk"),("Ezra","Nunc.lectus@ametconsectetuer.co.uk"),("Avram","Integer.id@vel.edu"),("Clayton","Proin.vel@adipiscingelitEtiam.org");
INSERT INTO `contacts` (`name`,`email`) VALUES ("Shana","velit.justo@Sedet.ca"),("Stuart","turpis.Aliquam@eutelluseu.co.uk"),("Arthur","Aliquam.vulputate.ullamcorper@lobortis.com"),("Jolie","pellentesque.massa@mi.edu"),("Hollee","erat@euismodacfermentum.co.uk"),("Xantha","eu.dolor.egestas@Fuscedolor.edu"),("Haley","sed.sapien@loremlorem.org"),("Fitzgerald","libero@temporarcu.edu"),("Shana","ultrices.posuere.cubilia@Aliquameratvolutpat.com"),("Wade","rutrum@luctusvulputate.co.uk");
INSERT INTO `contacts` (`name`,`email`) VALUES ("Macon","mattis.semper.dui@gravida.co.uk"),("Alexander","Curabitur.ut.odio@aenimSuspendisse.ca"),("Carly","egestas.a@acrisus.net"),("Vernon","erat@pharetrasedhendrerit.co.uk"),("Maggy","non.egestas@ornarelectus.org"),("Joy","placerat.orci@nuncIn.net"),("James","felis.ullamcorper@nectempusscelerisque.net"),("Odette","pulvinar@orcitinciduntadipiscing.co.uk"),("Dante","natoque@Vivamusnibhdolor.edu"),("Ivan","dapibus@erosProin.co.uk");